### ISSUE TITLE
Request: UDF File Entry/Extended File Entry modification tool

### ISSUE THREAD

**Issue by rajing** [pali/udftools#10]
I've been researching for the past two days and can't find a way to modify the file entry metadata associated with a file. I generate a UDF disk image in Linux but the users of this image are usually running Windows. I would like to set the Windows file permissions ("UDF NT ACL") from the Linux platform. I tried various permutations of Linux ACLs (chmod) but wasn't successful.

After further research I found that the spec states ACLs are stored as named streams. Is there an built-in way of modifying them?

**Comment by pali** [comment]
udftools does not provide any tool for ACLs nor for named streams. And looks like linux udf kernel driver does not support it neither (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/fs/udf/namei.c#n1352). You can try to ask Jan Kara, current maintainer of kernel driver, or on linux-fsdevel@vger.kernel.org mailing list.

**Comment by rajing** [comment]
Much appreciated. Thanks for pointing me in the right direction.

**Comment by pali** [comment]
If you find something let me know.
