### ISSUE TITLE
Porting to Darwin (macOS)

### ISSUE THREAD

**Issue by gmerlino** [pali/udftools#13]
Hi, any chance the tools are going to be ported for the Mac as well?

I noticed there is a fsck as (soon-to-be-merged?) PR: if it is too much effort for all the udftools package, could at least the filesystem checker be taken into consideration?

Let me try to add some perspective on the use cases.
According to this page:

[https://github.com/JElchison/format-udf/wiki/fsck-tools-for-UDF](https://github.com/JElchison/format-udf/wiki/fsck-tools-for-UDF)

both on Linux and Mac there is currently no UDF fsck available supporting filesystem repair, so the forthcoming fsck would (possibly) cover both user bases.

**Comment by pali** [comment]
Hi! I'm not going to write any ports for Apple systems.

**Comment by gmerlino** [comment]
Are you going to accept PRs for such a port?

**Comment by pali** [comment]
Depends on how invasive it would be.

**Comment by gmerlino** [comment]
Please check my PR (for udffsck only):

[https://github.com/argorain/udftools/pull/1
](https://github.com/argorain/udftools/pull/1)

I hope it is not invasive (at all, possibly).

Please let me know your opinion.

Thanks again for your help.

**Comment by pali** [comment]
I see there tons of unused defined and entries... why they are there? Plus license of those file say they can be distributed under CDDL. So it means they cannot be included into udftools which is distributed under GPLv2+ and therefore incompatible with CDDL.

**Comment by pali** [comment]
Is anybody working on this? If not I will close this issue.
