### ISSUE TITLE
Fake MBR inside UDF filesystem?

### ISSUE THREAD

**Issue by psusi** [pali/udftools#22]
mkudffs apparently creates a fake MBR in the filesystem that lists a single partition starting in sector 0.  If you format a whole device ( like a loop device ) then it looks like it has become partitioned.  parted considers this to be invalid, but apparently the kernel accepts it and creates a dummy partition that is an alias for the whole drive.  This confuses gnome-disks-utility and it won't let you reformat the partition because it sees the MBR inside it.  This also seems like a bad idea to have an aliased block device because you could mount the same filesystem twice and the already mounted check wouldn't see the other device.  Why does it do this and can it stop?

**Comment by pali** [comment]
See mkudffs.8 manpage, section WHOLE DISK VS PARTITION for detailed answer to your question.

It is for compatibility with Microsoft Windows systems and because UDF target is multiplatform R/W filesystem, this is the only option how to achieve compatibility with MS.

If gnome-disks-utility has problem with such thing, it should be modified/fixed. When I was implementing this fake MBR partition table, I checked that existing Linux, Windows and Mac OS X tools are able to recognize, use and automatically mount such UDF formatted disk without any hacks. But gnome-disks-utility I have not tested.

**Comment by psusi** [comment]
If you want compatibility with Windows, then you shuoldn't be formatting the whole disk.  I would have thought that was obvious.  I don't think the problems this causes are limited to gnome-disks-utility.  As I mentioned before, having two different block devices that alias to the same data can allow you to accidentally mount it twice and blow up the fs.  It also causes confusion as to which one should be mounted, and which one should claim the UUID.  It also just seems wrong that you tried to format the whole disk and suddenly it is now partitioned and your whole disk filesystem is in partition 1.

**Comment by pali** [comment]
> you shuoldn't be formatting the whole disk

UDF requires to format whole disk.

> I would have thought that was obvious.

I thought that it is obvious that it is need to create that fake MBR. This is the only solution how to provide R/W compatibility across operating systems.

> I don't think the problems this causes are limited to gnome-disks-utility. As I mentioned before, having two different block devices that alias to the same data can allow you to accidentally mount it twice and blow up the fs. It also causes confusion as to which one should be mounted, and which one should claim the UUID. It also just seems wrong that you tried to format the whole disk and suddenly it is now partitioned and your whole disk filesystem is in partition 1.

So it is the time to fix these problems?

**Comment by pali** [comment]
> having two different block devices that alias to the same data can allow you to accidentally mount it twice

That is not truth. You cannot mount it twice.

**Comment by psusi** [comment]
On 8/31/2018 11:51 AM, pali wrote:
> UDF requires to format whole disk.

What gave you that idea?  Windows *requires* it to be inside a
partition, which is why you need the fake MBR *if* you format the whole
disk.  Linux doesn't care either way.

**Comment by psusi** [comment]
On 8/31/2018 12:12 PM, pali wrote:
> That is not truth. You cannot mount it twice.

Well I'll be... I could have sworn the already mounted check was based
on matching the dev_t, which is different for the two devices.  I wonder
how it works then...

**Comment by pali** [comment]
> What gave you that idea?

UDF itself. And Apple systems enforce it.

> I wonder how it works then...

IIRC partitions are holders of whole block device and you cannot mount whole device if holders are mounted and vice versa.

**Comment by psusi** [comment]
On 8/31/2018 2:19 PM, pali wrote:
> UDF itself. And Apple systems enforce it.

You mean on an optical disk?  Or do you really mean that if you want to
use UDF on a hard disk and have a mac recognize it, you must dedicate
the entire drive to it?  That would be incredibly stupid.

**Comment by pali** [comment]
Yes! Have not you read detailed answer in manpage?

**Comment by pali** [comment]
Well, I think it is clear now. So I'm closing this.

**Comment by psusi** [comment]
Wow... good to see Apple continuing to lead the world in stupidity.  Thanks for the answer.  On the other hand, could mkudffs not apply the fake MBR *only* when formatting a whole disk?

**Comment by psusi** [comment]
Nevermind... it's already not a problem when it's in a partition.

**Comment by pali** [comment]
> could mkudffs not apply the fake MBR *only* when formatting a whole disk?

See manpage, that is the default behavior. Fake MBR is put only when formatting whole non-removable disks.

**Comment by pali** [comment]
> Apple continuing to lead the world in stupidity.

This is not a stupidity now. It is correct implementation of standard. Here Linux implementation is less compliant.

**Comment by psusi** [comment]
Then the standard is stupid, as is apple for following it.  A filesystem doesn't get to say what goes on outside of its partition.  Requiring that you not have a partition table means you can't say, dual boot macOS and Linux or Windows ( or hell, triple boot ), and have a shared UDF partition where you can access your data from all 3 OSes.  UDF is relegated to removable media only.
