### ISSUE TITLE
Build instructions incomplete

### ISSUE THREAD

**Issue by DanMan** [pali/udftools#24]
I needed to create a `config/` folder myself before even the `autogen.sh` would run and I had to install `libtool` so that `libtoolize` would work.

**Comment by pali** [comment]
> configure.ac:10: error: possibly undefined macro: AC_DISABLE_SHARED                                                                                                                                                              
>      If this token and others are legitimate, please use m4_pattern_allow.                                                                                                                                                      
>      See the Autoconf documentation.

`sudo apt-get install libtool`
