### ISSUE TITLE
Coasters with 2.0

### ISSUE THREAD

**Issue by kickerofelves** [pali/udftools#28]
Can I get some advice on how to properly make images burnable to a bdr please?
My procedure has been based on steps widely available on the net such as 
http://www.troubleshooters.com/linux/blu-ray-backup.htm or https://wiki.gentoo.org/wiki/CD/DVD/BD_Writing
1. truncate -o --size=`du -B4096|cut -f1` bluray.udf
2. mkudffs -l "`date +%F-%H-%M-%S`" bluray.udf
3. mount the image using with fstab entry: /home/user/bluray.udf /media/BR  udf  loop,noauto,user,noatime,nodiratime         0       0
4. copy over files and unmount

This worked with udftools 1.x but not with 2.x. When I try to mount a bdr burned with 2.x I get: 
"mount: /media/cdrom0: wrong fs type, bad option, bad superblock on /dev/sr0, missing codepage or helper program, or other error."

**Comment by pali** [comment]
For BD discs you need to use UDF revision 2.50 or 2.60. mkudffs does not support yet creating UDF 2.50+ images. Moreover Linux kernel udf.ko driver does not support mounting UDF 2.50+ filesystem in R/W mode; only in read-only mode. mkudffs since version 2.0 has experimental support for creating BD-R images (not BD-ROM, not BD-RW), but currently I do not know any linux software which can append new files into BD-R images.


> 2. mkudffs -l "date +%F-%H-%M-%S" bluray.udf

This will format image file `bluray.udf` for harddisks, not for BD, as you have not specified `--media-type`. See `--media-type=` option in manual page.

**Comment by pali** [comment]
Maybe udfclient software can append new files into BD-R optical discs. But you need to experiment and try it. E.g. Debian has udfclient package in its repository.

**Comment by kickerofelves** [comment]
Sorry, I can only test on weekends. I don't want to append new files to BDR disc. I want to make a udf image and burn that image to a BDR disc. That disc will then only be mounted read-only to retrieve files. This is what I did prior to 2.0. Can you please tell me how to do this after 2.0?

> This will format image file bluray.udf for harddisks, not for BD, as you have not specified --media-type. See --media-type= option in manual page.

Sorry I don't understand. If I use "-m bdr" it needs udf revision 2.50 or higher but the manpage states 2.01 is the highest support for writing in Linux and udftools is for Linux (Linux tools for UDF filesystems). Mkudffs requires something more than what is possible?

**Comment by pali** [comment]
> Mkudffs requires something more than what is possible?

No, this is requirement by Blu-ray discs. UDF on Blu-ray needs to be in revision 2.50 or 2.60.

And mkudffs is not able to create standalone BD-ROM image with prepared files/content yet.

**Comment by kickerofelves** [comment]
So what was I making with mkudffs 1.x?

**Comment by pali** [comment]
Going to look at it...

**Comment by pali** [comment]
Ok, so mkudffs prior to version 1.1 used default blocksize of 2048 bytes, media type r/w harddisk and udf revision 2.01. So by above your commands you have created UDF 2.01 harddisk R/W image with 2K blocksize.

Optical discs have 2K blocksize and Linux kernel can read UDF 2.01 R/W filesystem in read-only mode of any type (including harddisk) from any block device (including optical discs, e.g. Blu-Ray). So this is probably reason why it worked.

But such created UDF image is not compliant for Blu-Ray optical discs and probably would not it be possible to read in other devices / operating systems which implements Blu-Ray according to standards.

**Comment by kickerofelves** [comment]
Thank you for the explanation. It seems writing a BDR data disc with native support for large file sizes is not possible in Linux. It also remains a mystery why it worked before but I get an error message now mounting the discs. Then and now UDF 2.01, block size 2K, hd image type. If I changed the block size (though I thought I tried it) to 512 would it work even if not compliant?

**Comment by pali** [comment]
You need to try what would happen... Non-compliant discs do not have to work, but could on some systems. I know that Windows and Apple's systems enfore that UDF blocksize must match media logical block/sector size. On linux you can specify `-o bs=...` to specify UDF blocksize. For more details about block size, see mkudffs manpage, section BLOCK SIZE.

**Comment by kickerofelves** [comment]
I decided to downgrade to 1.3 since that works. I'll use up my current supply of discs while I search for an alternative archival method. Thank you pali for your help!
