### ISSUE TITLE
Linking flag needed : -lreadline

### ISSUE THREAD

**Issue by Siltaar** [pali/udftools#39]
To compile wrudf I needed to edit the Makefile in order to add : `LDFLAGS="-lreadline"`
This was not needed with @argorain 's fork.

**Comment by pali** [comment]
Could you please describe why you need to edit Makefile? What is the issue/error?

**Comment by Siltaar** [comment]
Editing the `wrudf/Makefile` was a bad workaround, as it is a generated file.

Without the `-lreadline` value in the `LDFLAGS` variable in this file, the general `make` compilation fails in the `wrudf`folder with the following issue :
`wrudf.c:87: undefined reference to `readline'`

But it works with argorain fork of the repo.
I'm using Debian stable 10.2.

**Comment by pali** [comment]
What version of udftools are you using? Also please provide whole output from configure and make phase. configure already does autodetection if readline is present in system and enable its usage only if is working. wrudf can be compiled also without readline support when configure does not find working readline library.

**Comment by Siltaar** [comment]
I used a `git clone` version from 2 weeks ago.

I made a new clone, got another (maybe related) result :

```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking whether ln -s works... yes
./configure: line 8873: PKG_PROG_PKG_CONFIG: command not found
./configure: line 8875: syntax error near unexpected token `READLINE,'
./configure: line 8875: `  PKG_CHECK_MODULES(READLINE, readline, readline_found=yes, readline_found=no)'
```

**Comment by pali** [comment]
> ```
> ./configure: line 8873: PKG_PROG_PKG_CONFIG: command not found
> ./configure: line 8875: syntax error near unexpected token `READLINE,'
> ./configure: line 8875: `  PKG_CHECK_MODULES(READLINE, readline, readline_found=yes, readline_found=no)'
> ```

This looks like you have not installed `pkg.m4` macro file from pkg-config project prior to running autoconf. You need to install it when running autoconf.

Or use officially released udftools tarballs with correctly generated configure script.

**Comment by Siltaar** [comment]
Where whose tarballs can be found ?

There is no link to an official website in the README, nor wiki in this Github project…

Edit: I wanted to test the state of the art `fsck.udf` for Debian, and everything want smooth with argorain udftools clone (despite the fact that the `udffsck` utility did not manage to fix my broken UDF image).

**Comment by pali** [comment]
Standard github "releases" button on main github project page. (Maybe now after github updated UI, it is not easy to find.

Github has now 6 main buttons: commits, branches, packages, releases, contributor, license (on every project page)

Direct link: https://github.com/pali/udftools/releases

**Comment by Siltaar** [comment]
Thank you. I don't see this mechanism in action often enough to remember it.

For the audience : between the tabs and the actual buttons, there are another line of "important links", with currently 9 releases at the counter for `udftools`.
