### ISSUE TITLE
How do I extract UDF iso?

### ISSUE THREAD

**Issue by Silezmogul** [pali/udftools#42]
Conventional extraction tools don't do the job. How do I extract UDF iso?

**Comment by Silezmogul** [comment]
Nvm - mount, copy, paste.

**Comment by pali** [comment]
Do you want to extract UDF or ISO (9660)?

**Comment by pali** [comment]
Any filesystem supported by linux kernel can be extracted by mounting it; including iso9660 and also udf. For userspace extracting without kernel support, you can use for udf fs **udfclient** from the web http://13thmonkey.org/udfclient/ and for iso9660 you can use **iso-read** from project http://www.gnu.org/software/libcdio/
