### ISSUE TITLE
Maybe include cdmrw.c

### ISSUE THREAD

**Issue by ismail** [pali/udftools#5]
In openSUSE we also package the http://www.kernel.org/pub/linux/kernel/people/axboe/tools/cdmrw.c tool. It might make sense to import it too.

**Comment by pali** [comment]
What is that tool doing? I do not see any description of it and quick look did not helped me to understand what is that tool doing and for which action is needed.

And what has that tool common with UDF filesystem?

**Comment by ismail** [comment]
I asked Jens Axboe and he said it could be dropped. Sorry for opening a bug before asking the original author.

**Comment by pali** [comment]
@ismail Looking at this cdmrw.c tool and it basically just tell CD/DVD burner firmware to start formatting inserted CD/DVD optical media to [Mt Rainier](https://en.wikipedia.org/wiki/Mount_Rainier_(packet_writing)) format. So it is really something which does not belong to udftools. Mt Rainier is just another layer between filesystem and physical device which provides defect management, so is independent of UDF filesystem. Other filesystems can be put too on top of Mt Rainier. So this cdmrw.c tool should go into some project which provides another tools for CD/DVD disks, agnostic of used filesystem.
