### ISSUE TITLE
pktcdvd to be removed from kernel

### ISSUE THREAD

**Issue by GerryHickman** [pali/udftools#59]
udftools install creates a packet device on each optical drive, e.g. pktcdvd1, but the driver is being removed from kernel 6.x.

As I understand it, this will only affect older media types like cd-rw, but newer media types like DVD-RAM and BD-RE (plus hard drives) will continue to work.

udftools has subfoler 'pktsetup', which contains the udev rules, but the rules won't work if the kernel module is not there.

**Comment by pali** [comment]
> driver is being removed from kernel 6.x.

Why?

> As I understand it, this will only affect older media types like cd-rw, but newer media types like DVD-RAM and BD-RE (plus hard drives) will continue to work.

For CD-RW, DVD-RW and DVD+RW is pktcdvd required, there is no other option.

For DVD-RAM it is possible to directly mount /dev/sr0 but it is highly suggested to use pktcdvd because DVD drives firmwares had lot of times bad implementation of read-modify-write scheme.

**Comment by pali** [comment]
I'm still using this driver and userspace tools are still under active maintenance. So I do not understand why it is being removed, who and when decided it, and why nobody was informed about it.

**Comment by GerryHickman** [comment]
This is the page I read, and was surprised about it:

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/block?h=next-20221220&id=f40eb99897af665f11858dd7b56edcb62c3f3c67

**Comment by ghost** [comment]
As a workaround, the original driver could be maintained as an out of tree module for newer kernels.

**Comment by pali** [comment]
It is back in v6.2-rc3+:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4b83e99ee7092df37a5cf292fde976ebc475ea63

**Comment by suxpert** [comment]
Bad news from 2025: pktcdvd might be removed (again) in kernel 6.17.

https://www.phoronix.com/news/Linux-To-Remove-pktcdvd
https://www.linuxencaja.net/en/linux-6-17-plans-to-do-away-with-the-pktcdvd-driver-for-writing-packets-to-cd-dvd/
