### ISSUE TITLE
port fsck from illumos code

### ISSUE THREAD

**Issue by unxed** [pali/udftools#6]
https://github.com/illumos/illumos-gate/tree/master/usr/src/cmd/fs.d/udfs/fsck

**Comment by pali** [comment]
NAK. It supports only UDF 1.5 and depends on Solaris/Illumos kernel interface so it will never work on Linux. Also there fsck code in udftools repository https://github.com/pali/udftools/tree/87acf1a2306b7b60ed9d61b53c2a487ea5f3396c/src/chkudf which is not suitable for usage.
