### ISSUE TITLE
Add a README file

### ISSUE THREAD

**Issue by KingDuckZ** [pali/udftools#9]
Hi, can you please add a readme file? It would be very useful if it could clearly explain certain things, for example what UDF versions are supported, a couple command line usage examples, if it will work with a GUI (eg k3b), how to get in touch with the dev(s), what plans are there.

I would like to contribute, but I'm struggling to understand if there's anything I could do, or even if there's anything needed at all. I tried joining #udftools on IRC freenode but I think that room is unregistered.

**Comment by pali** [comment]
Hi! What are you expecting in readme file? Versions which are supported by mkudffs are documented in mkudffs manpage, together with all other features supported by mkudffs. If it is supported by k3b, I do not know, ask k3b people. My current plan is fixing mkudffs tool, specially interoperability with other operating systems (Microsoft's, Apple's), see git commits and doing regular maintenance of other tools. @argorain started working on fsck, see pull request. If you would like to contribute, feel free to ask. There is no IRC channel, but you can contact me directly via email.

**Comment by pali** [comment]
If you have any other questions, fell free to ask. I would close this issue for now.
